import React from "react";
import Head from "next/head";
import { useInView } from "react-intersection-observer";
import Link from "next/link";
import Header from "../components/Header";
import Hero from "../components/Hero";
import { useRouter } from "next/router";
import { client } from "../sanity/lib/client";
import { urlForImage } from "../sanity/lib/image";

import { Post } from "../typing";
import { Tooltip } from "react-tippy";
import { Footer } from "../components/Footer";
interface Props {
  posts: [Post];
}

export default function Home({ posts }: Props) {
  const { ref: myRef, inView: myelemisvisible } = useInView();
  const router = useRouter();

  return (
    <div className=" overflow-x-hidden">
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />

      <div className="mb-28">
        <div
          ref={myRef}
          className="wrapper p-2 lg:p-6"
        >
          <section className="relative isolate mx-auto w-full py-12 max-w-screen-xl pt-0">
            <div className="mx-auto grid grid-cols-[repeat(auto-fill,_minmax(305px,1fr))] place-items-center gap-x-4 gap-y-7 px-4 sm:gap-y-6 sm:px-8">      {posts.map((post) => (
              <PostCard2 post={post}></PostCard2>
              /*   <Link passHref key={post._id} href={`/post/${post.slug.current}`}>
                  {console.log('post.author.image', post.author.image)}
                  <div
                    className={`${
                      myelemisvisible
                        ? "group translate-x-[0] opacity-1 duration-500  border rounded-lg shadow-md cursor-pointer overflow-hidden"
                        : "group translate-x-[100px] opacity-0 duration-500 border rounded-lg shadow-md cursor-pointer overflow-hidden"
                    }`}
                  >
                    <img
                      className=" w-full h-60 object-cover group-hover:scale-105 transition-transform duration-200 ease-in-out"
                      src={post && post.mainImage && urlForImage(post.mainImage).url()}
                      alt="image"
                    />
                    <div className="flex justify-between p-5  bg-white">
                      <div>
                        <p className="text-lg font-bold">{post.title}</p>
                        <p className="text-sm">
                          {post.description} by{" "}
                          <span className="font-medium uppercase">
                            {post.author.name}
                          </span>
                        </p>
                      </div>
                      <img
                        className="h-12 ml-6 rounded-full"
                        src={post && post.author.image && urlForImage(post && post.author.image).url()}
                        alt=""
                      />
                    </div>
                  </div>
                </Link> */
            ))}
            </div>
          </section>


        </div>
      </div>
      {/* bottom section */}
      <Footer/>
      {/* bottom section */}
    </div>
  );
}

const PostCard2 = ({ post }) => {
  return (
    <a
      className="group relative grid aspect-square h-full w-full min-w-[297px] grid-rows-[1fr_64px] gap-3 overflow-hidden rounded-lg sm:grid-rows-[259px_64px]"
      href={`/post/${post.slug.current}`}>
      <div className="relative h-full w-full overflow-hidden">
        <div className="scrollbar-hide pointer-events-auto relative inset-0 flex snap-x snap-mandatory overflow-x-auto w-full rounded-lg object-cover h-full">
          <img
            src={post && post.mainImage && urlForImage(post.mainImage).url()}
            className="h-full w-full flex-none snap-center snap-always overflow-hidden object-cover"
            alt="Wander Big Sur Coast"
            width={297}
            height={259}
          />
          <div className="deal">

            <div className="right">
              <div className="prices price-display">
                <p className="deal-price-old">
                  <span className="price-container hotel-price">{post.priceRange.high}</span>
                </p>
                <p className="deal-price-new">
                  <span className="price-container hotel-price">{post.price}€</span>
                </p>
              </div>
              <div className="skip-rate-label">Tarif Travel.so</div>
            </div>
          </div>
        </div>

        <div className="flex max-w-[84px] items-center absolute bottom-0 left-1/2 z-40 -translate-x-1/2">
          <div className="flex w-full items-center overflow-x-hidden">
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              className="flex-none"
              style={{
                margin: 3,
                width: 6,
                height: 6,
                backgroundColor: "rgb(255, 255, 255)",
                borderRadius: 3,
                opacity: 1
              }}
            />
            <div
              className="flex-none"
              style={{
                margin: 3,
                width: 6,
                height: 6,
                backgroundColor: "rgb(255, 255, 255)",
                borderRadius: 3,
                opacity: "0.2"
              }}
            />
            <div
              className="flex-none"
              style={{
                margin: 3,
                width: 6,
                height: 6,
                backgroundColor: "rgb(255, 255, 255)",
                borderRadius: 3,
                opacity: "0.2"
              }}
            />
            <div
              className="flex-none"
              style={{
                margin: 3,
                width: 5,
                height: 5,
                backgroundColor: "rgb(255, 255, 255)",
                borderRadius: "2.5px",
                opacity: "0.2"
              }}
            />
            <div
              className="flex-none"
              style={{
                margin: 3,
                width: 4,
                height: 4,
                backgroundColor: "rgb(255, 255, 255)",
                borderRadius: 2,
                opacity: "0.2"
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
            <div
              style={{
                backgroundColor: "black",
                opacity: 0,
                width: 3,
                height: 3,
                margin: 3
              }}
            />
          </div>
        </div>
      </div>
      <div className="flex h-full flex-col justify-around">
        <div className="text-property-eyebrow text-black/60">
          <span className="bg-green-100 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 text-white">New</span>

        </div>
        <div className="mb-0.5 font-medium">{post.title}</div>
        <div className="flex items-center gap-2">
          <div className="text-5-v-light-grey border-3-primary-grey leading-xxs flex h-full items-center border-r text-[13px] group-hover:text-black">
            <span className="whitespace-nowrap pr-2">
              à partir de {post.price}€
            </span>
          </div>
          <div className="flex items-center gap-2 text-sm">
            <div className="flex flex-wrap items-center justify-center gap-1">
            <span className=" text-gray-800 text-xs font-medium inline-flex items-center px-2.5  rounded mr-2 border border-gray-500">
                      <svg
                        className="w-2.5 h-2.5 mr-1.5"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                      >
                        <path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0Zm3.982 13.982a1 1 0 0 1-1.414 0l-3.274-3.274A1.012 1.012 0 0 1 9 10V6a1 1 0 0 1 2 0v3.586l2.982 2.982a1 1 0 0 1 0 1.414Z" />
                      </svg>
                      Il y a 3 heures
                    </span>
            </div>


          </div>

        </div>
      </div>
    </a>
  )
}

const PostCard = ({ post }) => {
  return (
    <a
      className="group relative grid aspect-square h-full w-full min-w-[297px] grid-rows-[1fr_64px] gap-3 overflow-hidden rounded-lg sm:grid-rows-[259px_64px]"
      href={`/post/${post.slug.current}`}
    >
      <div className="relative h-full w-full overflow-hidden">
        <div className="scrollbar-hide pointer-events-auto relative inset-0 flex snap-x snap-mandatory overflow-x-auto w-full rounded-lg object-cover h-full">

          <img
            src={post && post.mainImage && urlForImage(post.mainImage).url()}
            className="h-full w-full flex-none snap-center snap-always overflow-hidden object-cover"
            alt={post.title}
            width={297}
            height={259}
            loading="eager"
          />

        </div>
        {/* Additional UI components can be added here as per the original JSX */}
      </div>
      <div className="flex h-full flex-col justify-around">
        <div className="text-property-eyebrow text-black/60">
          {/* Location data could be added here */}
        </div>
        <div className="mb-0.5 font-medium">{post.title}</div>
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2 text-sm">
            <div className="flex flex-wrap items-center justify-center gap-1">
              {/* SVG icons and additional data could be added here */}
            </div>
          </div>
        </div>
      </div>
    </a>
  );
};


export async function getStaticProps() {
  const query = `
  *[_type=="post"]{
    _id,
    title,
    
    author -> {
    name,
    image
  },
  
  description,
  mainImage,
  slug,
  price,
  priceRange
  }`;
  //const query = `[_type == 'post']`
  const posts = await client.fetch<Post[]>(query,
    {
      next: {
        revalidate: 3600 // look for updates to revalidate cache every hour
      }
    }
  );
  console.log('posts', posts)
  if (!posts) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      posts,
    },
  };
}

function HomePhone() {
  return (
    <svg
      className="cursor-pointer text-gray-800 hover:text-black duration-100"
      width="24"
      height="24"
      fill="none"
      aria-label="home"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.72 2.93a.45.45 0 0 1 .56 0l.34-.43-.34.43 9.37 7.5a.56.56 0 1 0 .7-.86l-9.38-7.5a1.55 1.55 0 0 0-1.94 0l-9.38 7.5a.56.56 0 0 0 .7.86l9.37-7.5zm7.17 9.13v-1.4l.91.69a.5.5 0 0 1 .2.4V20a2 2 0 0 1-2 2h-4a.5.5 0 0 1-.5-.5V17a1 1 0 0 0-1-1h-1a1 1 0 0 0-1 1v4.5a.5.5 0 0 1-.5.5H6a2 2 0 0 1-2-2v-8.25a.5.5 0 0 1 .2-.4l.91-.68V20c0 .5.4.89.89.89h3.39V17a2.11 2.11 0 0 1 2.11-2.11h1A2.11 2.11 0 0 1 14.61 17v3.89H18a.89.89 0 0 0 .89-.89v-7.95z"
        fill="#A8A8A8"
      ></path>
    </svg>
  );
}
function Homee() {
  return (
    <svg
      className="cursor-pointer text-gray-800 hover:text-black duration-100"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      aria-label="home"
    >
      <path
        d="M4.5 21.25V10.87c0-.07.04-.15.1-.2l7.25-5.43a.25.25 0 0 1 .3 0l7.25 5.44c.06.04.1.12.1.2v10.37c0 .14-.11.25-.25.25h-4.5a.25.25 0 0 1-.25-.25v-5.5a.25.25 0 0 0-.25-.25h-4.5a.25.25 0 0 0-.25.25v5.5c0 .14-.11.25-.25.25h-4.5a.25.25 0 0 1-.25-.25z"
        fill="currentColor"
        stroke="currentColor"
        strokeLinejoin="round"
      ></path>
      <path
        d="M22 9l-9.1-6.83a1.5 1.5 0 0 0-1.8 0L2 9"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
      ></path>
    </svg>
  );
}

function Search() {
  return (
    <svg
      className="cursor-pointer text-gray-800 hover:text-black duration-100"
      width="25"
      height="24"
      fill="none"
      aria-label="search"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.8 10.69a6.95 6.95 0 1 1 13.9 0 6.95 6.95 0 0 1-13.9 0zm6.95-8.05a8.05 8.05 0 1 0 5.13 14.26l3.75 3.75a.56.56 0 1 0 .79-.79l-3.73-3.73a8.05 8.05 0 0 0-5.94-13.5z"
        fill="#A8A8A8"
      ></path>
    </svg>
  );
}

function Readinglist() {
  return (
    <svg
      className="cursor-not-allowed text-gray-800 hover:text-black duration-100"
      width="25"
      height="24"
      viewBox="0 0 25 25"
      fill="none"
      aria-label="Reading list"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10 3a2 2 0 0 0-2 2v1H6a2 2 0 0 0-2 2v14a.5.5 0 0 0 .8.4l5.7-4.4 5.7 4.4a.5.5 0 0 0 .8-.4V8a2 2 0 0 0-2-2H9V5a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v12a.5.5 0 1 0 1 0V5a2 2 0 0 0-2-2h-9zM5 8a1 1 0 0 1 1-1h9a1 1 0 0 1 1 1v12.98l-5.2-4a.5.5 0 0 0-.6 0l-5.2 4V8z"
        fill="#757575"
      ></path>
    </svg>
  );
}
